### PR TITLE
Fix/cleanup chassis bootparam and bootdev options

### LINKED ISSUE #163: Unable to set options=efiboot,persistent
I'm thinking the parsing of multiple "options=" values is somehow broken.

When I do the following:
```
ipmitool -I lanplus chassis bootdev disk options=persistent,efiboot -vvv
```

I see the following
```
<snip>
Chassis Set Boot Parameter 4 to 0101

>> Sending IPMI command payload
>>    netfn   : 0x00
>>    command : 0x08
>>    data    : 0x05 0xa0 0x08 0x00 0x00 0x00
<snip>
```
Notice the data is ``0x05 0xa0 ...``  0xA0 means EFI but NOT persistent.

When doing the command:
```
ipmitool -I lanplus chassis bootdev disk options=efiboot,persistent -vvv
```

I see:
```
<snip>
Chassis Set Boot Parameter 4 to 0101

>> Sending IPMI command payload
>>    netfn   : 0x00
>>    command : 0x08
>>    data    : 0x05 0xc0 0x08 0x00 0x00 0x00
<snip>
```
Notice the data is ``0x05 0xc0 ...``   0xC0 means persistent but NOT EFI

What we desire should look like this for either call:
```
Chassis Set Boot Parameter 4 to 0101

>> Sending IPMI command payload
>>    netfn   : 0x00
>>    command : 0x08
>>    data    : 0x05 0xe0 0x08 0x00 0x00 0x00
```
The data should be ``0x05 0xe0 ...``  0xE0 means EFI and persistent

The values are specified in Table 28-14 `Boot Option Parameters` in the IPMI Specification, V2.0, Rev. 1.1 https://www.intel.com/content/dam/www/public/us/en/documents/product-briefs/ipmi-second-gen-interface-spec-v2-rev1-1.pdf

### PR DESCRIPTION
**Pull request by AlexanderAmelkin**
This resolves #163 and also cleans up `chassis bootparam get` decoding and `chassis bootdev options=...` parsing.

Please read individual commit messages.

### CODE REVIEW

**Comment by AlexanderAmelkin** [comment]
@jvillal-amp, please check if this works for you.

File: lib/ipmi_chassis.c [hunk 1]
```diff
@@ -1712,6 +1712,205 @@ ipmi_chassis_set_bootflag_help()
...
 
+/*
+ * Sugar. Macros for internal use by bootdev_parse_options() to make
+ * the structure initialization look better
+ */
+#define BF1_OFFSET 0
+#define BF2_OFFSET 1
+#define BF3_OFFSET 2
+#define BF4_OFFSET 3
+#define BF_BYTE_COUNT 5
```
Comment (jvillal-amp) [inline lib/ipmi_chassis.c]: Random thought: If they were like 
```
static const int BF1_OFFSET = 0
```

Then they would be contained within the scope of this function and also type safe.

But also good to leave as is.

File: lib/ipmi_chassis.c [hunk 2]
```diff
@@ -1712,6 +1712,205 @@ ipmi_chassis_set_bootflag_help()
...
+
+/* A helper for ipmi_chassis_main() to parse bootdev options */
+static
+bool
+bootdev_parse_options(char *optstring, uint8_t flags[])
+{
+	char *token;
+	char *saveptr = NULL;
+	int optionError = 0;
+	static struct {
```
Comment (vmauery) [inline lib/ipmi_chassis.c]: static const struct?

File: lib/ipmi_chassis.c [hunk 3]
```diff
@@ -1700,98 +2057,13 @@ ipmi_chassis_main(struct ipmi_intf * intf, int argc, char ** argv)
...
-					}
-				}
-				if (!op->name) {
-					/* Option not found */
-					optionError = 1;
-					lprintf(LOG_ERR, "Invalid option: %s", token);
-				}
-				token = strtok_r(NULL, ",", &saveptr);
+				uint8_t flags[BF_BYTE_COUNT];
+				if (!bootdev_parse_options(argv[2] + 8, flags))
```
[the remark this answers is not in the document]
Comment (JohnVillalovos) [reply lib/ipmi_chassis.c]: > 
> 
> What is 8?

The length of "options=", but agree that it isn't obvious.

File: lib/ipmi_chassis.c (hunk 1 above)
Comment (AlexanderAmelkin) [reply lib/ipmi_chassis.c]: Good point

File: lib/ipmi_chassis.c [hunk 4]
```diff
@@ -1554,6 +1712,205 @@ ipmi_chassis_set_bootflag_help()
...
+	char *token;
+	char *saveptr = NULL;
+	int optionError = 0;
+	static struct {
+		char *name;
+		off_t offset;
+		unsigned char mask;
+		unsigned char value;
+		char *desc;
+	} *op, options[] = {
```
[the remark this answers is not in the document]
Comment (AlexanderAmelkin) [reply lib/ipmi_chassis.c]: Not my code (I only moved `*op` before `options`), but I agree.

File: lib/ipmi_chassis.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (AlexanderAmelkin) [reply lib/ipmi_chassis.c]: I agree. Hate magic numbers myself. Not my `8` originally, but I though in this case where it is adjacent to `strcmp` and the `"options="` string, it's not that of a crime. I guess a comment would suffice. Will add one.

File: lib/ipmi_chassis.c (hunk 2 above)
Comment (AlexanderAmelkin) [reply lib/ipmi_chassis.c]: Agreed

File: lib/ipmi_chassis.c (hunk 1 above)
Comment (AlexanderAmelkin) [reply lib/ipmi_chassis.c]: Alas, it turned out that gcc5 (default for Ubuntu Xenial) can't use `static const int` for structure initialization. gcc8 can do that, but for compatibility I'll keep these as macros.
